package com.example.firebasetorecyclerview;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import com.google.android.gms.tasks.OnFailureListener;
import com.google.android.gms.tasks.OnSuccessListener;
import com.google.firebase.database.FirebaseDatabase;

import java.util.HashMap;

/// this class is used for add the data
public class addActivity extends AppCompatActivity {
EditText name , course , email , purl;
Button add , back;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_update_actvity);
        add = findViewById(R.id.addbtn);
        back = findViewById(R.id.backbtn);
        name = findViewById(R.id.addnameu);
        course = findViewById(R.id.addcourseu);
        email = findViewById(R.id.addemailu);
        purl = findViewById(R.id.addpurlu);
        back.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent(addActivity.this , MainActivity.class);
                startActivity(intent);
                finish();
            }
        });
        add.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                processInsert();

            }
        });
    }

    private void processInsert() {
        // here we are using hash map instead of using of the model class becoz
//        its make more simpler for us to use data
        HashMap<String , Object> map = new HashMap<>();
        map.put("name" , name.getText().toString());
        map.put("course" , course.getText().toString());
        map.put("email" , email.getText().toString());
        map.put("purl" , purl.getText().toString());
      // initially we are adding all the entry manually there is no any id generated but now we have to generate the id
        // id generated by push method
        FirebaseDatabase.getInstance().getReference().child("students").push()
                .setValue(map)
         // now implements two method on success ans in failure
                .addOnSuccessListener(new OnSuccessListener<Void>() {
                    @Override
                    public void onSuccess(Void unused) {
                       // after success all are get blanks
                        name.setText("");
                        email.setText("");
                        course.setText("");
                        purl.setText("");
                        Toast.makeText(addActivity.this, "New data inserted", Toast.LENGTH_LONG).show();
                         startActivity(new Intent(addActivity.this , MainActivity.class));
                    }
                })
                .addOnFailureListener(new OnFailureListener() {
                    @Override
                    public void onFailure(@NonNull Exception e) {
                        Toast.makeText(addActivity.this, "Not inserted", Toast.LENGTH_SHORT).show();
                    }
                });

     }
}